---
kind: pipeline
name: rustfmt

steps:
- name: rustfmt
  image: rust:latest
  commands:
    - rustup component add rustfmt
    - cargo fmt -- --check
- name: matrix-notification
  image: plugins/matrix
  pull: always
  settings:
    roomid: qOcHPTCOgAbkObQgRy:matrix.org
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
  when:
    status:
    - failure
---
kind: pipeline
name: test

depends_on:
- rustfmt

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --recursive --init
- name: test
  image: rust:latest
  pull: always
  environment:
    RUST_BACKTRACE: 1
    GIT_AUTHOR_EMAIL: drone@exqa.de
    GIT_AUTHOR_NAME: drone
  commands:
  - apt-get update && apt-get install -y libgtk-3-dev gettext appstream-util desktop-file-utils meson
  - meson _build
  - ninja -C _build test

- name: matrix-notification
  image: plugins/matrix
  pull: always
  settings:
    roomid: qOcHPTCOgAbkObQgRy:matrix.org
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
  when:
    status:
    - failure
---
kind: signature
hmac: 1aee2648dce021a6e4e82317c278d35e8669052b67e07c9b5a6f8939b4aa7fb7

...
