---
kind: pipeline
name: QA

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --recursive --init
- name: rustfmt
  image: rust:latest
  commands:
    - rustup component add rustfmt
    - cargo fmt -- --check
- name: clippy
  image: rust:latest
  pull: always
  environment:
    RUST_BACKTRACE: 1
    GIT_AUTHOR_EMAIL: drone@exqa.de
    GIT_AUTHOR_NAME: drone
  commands:
    - apt-get update && apt-get install -y libgtk-3-dev gettext
    - rustup component add clippy
    - cargo clippy
- name: matrix-notification
  image: plugins/matrix
  pull: always
  settings:
    roomid: qOcHPTCOgAbkObQgRy:matrix.org
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
  when:
    status:
    - failure
---
kind: pipeline
name: test

depends_on:
  - QA

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --recursive --init
- name: test
  image: rust:latest
  pull: always
  environment:
    RUST_BACKTRACE: 1
    GIT_AUTHOR_EMAIL: drone@exqa.de
    GIT_AUTHOR_NAME: drone
  commands:
  - apt-get update && apt-get install -y libgtk-3-dev gettext appstream-util desktop-file-utils meson
  - meson _build
  - ninja -C _build test

- name: matrix-notification
  image: plugins/matrix
  pull: always
  settings:
    roomid: qOcHPTCOgAbkObQgRy:matrix.org
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
  when:
    status:
    - failure
---
kind: signature
hmac: cc5ebed62f517b06c4370fd45e841f555eba314886c729458dc125de18aafe90

...
