image: rust:latest

stages:
  - qa
  - test

variables:
  RUST_BACKTRACE: 1
  GIT_AUTHOR_EMAIL: ci@gitlab.gnome.org
  GIT_AUTHOR_NAME: GNOME CI
  GETTEXT_BIN_DIR : /usr/bin
  GETTEXT_LIB_DIR: /usr/lib/gettext
  GETTEXT_INCLUDE_DIR: /usr/include

before_script:
  - apt-get update -qq && apt-get install -y libgtk-3-dev gettext appstream-util desktop-file-utils meson

qa:
  stage: qa
  script:
    - rustup component add rustfmt
    - rustup component add clippy
    - cargo fmt -- --check
    - cargo clippy

test-native:
  stage: test
  script:
    - apt-get install -y cmake libfreetype6-dev libfontconfig1-dev # required for tests
    - meson _build
    - ninja -C _build test

test-cross:
  stage: test
  variables:
    CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER: arm-linux-gnueabihf-gcc
    PKG_CONFIG_ALLOW_CROSS: 1
    PKG_CONFIG_PATH: /usr/lib/arm-linux-gnueabihf/pkgconfig/
    RUST_TARGET: armv7-unknown-linux-gnueabihf
    CARGO_BUILD_TARGET : armv7-unknown-linux-gnueabihf
  script:
    - dpkg --add-architecture armhf
    - apt-get update && apt-get upgrade -y
    - apt-get install -y aptitude
    - aptitude install -y gcc-arm-linux-gnueabihf
    - aptitude install -y libgtk-3-dev:armhf # Install GTK and its dependencies
    - aptitude install -y pkg-config # Reinstall pkg-config as aptitude will have uninstalled it for GTK
    - rustup target add armv7-unknown-linux-gnueabihf
    - apt-get install -y gettext appstream-util desktop-file-utils meson libglib2.0-bin # native deps of gxi
    - meson build
    - ninja -C build # Can't run tests for crosscompiled binaries
