language: rust

env:
  matrix:
    - DIST: "xenial"
    - DIST: "bionic"

matrix:
  include:
    - os: linux
      rust: nightly
    - os: linux
      rust: beta
    - os: linux
      rust: stable
sudo: true
addons:
  apt:
    packages:
    - libgtk-3-dev
before_install:
  - docker run -d --name ubuntu-test -v $(pwd):/travis ubuntu:$DIST tail -f /dev/null
  - docker ps
install:
  - docker exec -t ubuntu-test bash -c "apt-get update;
    apt-get install -y libgtk-3-dev;"
script:
  - docker exec -t ubuntu-test bash -c "rustc --version &&
    cargo test &&
    cargo doc &&
    cargo build &&
    git diff -R --exit-code"
