language: rust
cache: cargo
matrix:
  include:
    - os: linux
      rust: nightly
    - os: linux
      rust: beta
    - os: linux
      rust: stable
    - os: osx
      rust: nightly
    - os: osx
      rust: beta
    - os: osx
      rust: stable
sudo: true
addons:
  apt:
    packages:
    - libgtk-3-dev
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gtk+3 cairo atk; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig;
    fi
script:
  - rustc --version
  - cargo test
  - cargo doc
  - cargo build
  - git diff -R --exit-code
