sudo: true
dist: bionic
language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
addons:
  apt:
    packages:
    - libgtk-3-dev
    - cmake
    - libpango1.0-dev
before_install:
  sudo apt-get install libgtk-3-dev cmake libpango1.0-dev