sudo: true
env:
  matrix:
    - DIST: "xenial"
    - DIST: "bionic"
  matrix:
    - RUST_VER: "stable"
    - RUST_VER: "nightly"
addons:
  apt:
    packages:
    - libgtk-3-dev
before_install:
  - docker run -d --name ubuntu-test -v $(pwd):/travis ubuntu:$DIST tail -f /dev/null
  - docker ps
install:
  - docker exec -t ubuntu-test bash -c "apt-get update;
    apt-get install -y libgtk-3-dev;"
script:
  - docker exec -t ubuntu-test bash -c "(curl https://sh.rustup.rs -sSf | sh) &&
    rustup install $RUST_VER &&
    rustc --version &&
    cargo test &&
    cargo doc &&
    cargo build &&
    git diff -R --exit-code"
