sudo: true
language: rust
env:
  matrix:
    - DIST: "disco"
      RUST_VER: "stable"
    - DIST: "disco"
      RUST_VER: "nightly"
    - DIST: "bionic"
      RUST_VER: "stable"
    - DIST: "bionic"
      RUST_VER: "nightly"

before_install:
  - docker run -d --name ubuntu-test -v $(pwd):/travis ubuntu:$DIST tail -f /dev/null
  - docker ps
install:
  - docker exec -t ubuntu-test bash -c "apt-get update;
    apt-get install -y libgtk-3-dev cmake gcc g++ curl;"
script:
  - docker exec -t ubuntu-test bash -c "(curl https://sh.rustup.rs -sSf | sh -s -- -y) &&
    source \$HOME/.cargo/env &&
    cd /travis &&
    rustup install $RUST_VER &&
    rustc --version &&
    cargo test &&
    cargo doc &&
    cargo build"
