sudo: true
language: rust
env:
  matrix:
  - DIST: disco
    RUST_VER: stable
  - DIST: disco
    RUST_VER: nightly
  - DIST: bionic
    RUST_VER: stable
  - DIST: bionic
    RUST_VER: nightly
deploy:
  provider: script
  script: bash scripts/deploy-docs.sh
  on:
    branch: master
addons:
  ssh_known_hosts:
  - 207.180.196.127
before_install:
- openssl aes-256-cbc -K $encrypted_63d4c9a7115b_key -iv $encrypted_63d4c9a7115b_iv
  -in .travis/id_ed25519.enc -out .travis/id_ed25519 -d
- docker run -d --name ubuntu-test -v $(pwd):/travis ubuntu:$DIST tail -f /dev/null
- docker ps
install:
- docker exec -t ubuntu-test bash -c "apt-get update; apt-get install -y libgtk-3-dev
  gettext appstream-util desktop-file-utils gcc g++ curl meson;"
script:
- travis_wait 45 docker exec -t ubuntu-test bash -c "(curl https://sh.rustup.rs -sSf
  | sh -s -- -y) && source \$HOME/.cargo/env && cd /travis && rustup install $RUST_VER
  && rustc --version && meson _build && ninja -C _build test && cargo rustdoc -- --document-private-items"
