sudo: true
language: rust
env:
  matrix:
  - DIST: disco
    RUST_VER: stable
  - DIST: disco
    RUST_VER: nightly
  - DIST: bionic
    RUST_VER: stable
  - DIST: bionic
    RUST_VER: nightly
deploy:
  provider: script
  script: bash scripts/deploy-docs.sh
  skip-cleanup: true
  keep-history: true
  verbose: true
  on:
    branch: master
addons:
  ssh_known_hosts:
    secure: BbHIKWh0kjwqHTrl+RNnhbqcXiAd6OHHpT5Bk7QiQuFW/x28iTb72vgjwLIx9Lbf8BKND09iLkdVthTnXqYr1v+CnmEsIYA/eaYgg0necgJfb3dE2K1/xsdYteptrtI/N8IKz1/VEYltUcsrrhTgWs9V/3iw/92v+jhiRfxC+DmfPiTvUJUjfHzVQ68WsAoNUw+Uhq3zpcDo4vtLihMrlXxkpH20U37dGv8Xh6DDdDG+mgkd5OFlaI/67/IM3nreEv8TTJGm+qLRcTnxJuLOZOWINYBEyjLixTYQ4vaGFppD/5NDsoRtyR2NOZEcmfrRgzYUs/JWXD0qeRkT+NTOkUmIc6Au62KYCibgRpaPhYdk+81d4UGVrJ2qjoU0PlSlBD3IGb0lohSw+FqO8f9E9qKBETtm09RDYjtG9L+u3fH9hqrHKwW+woAaiGroqyqR1S+ojZe+rFbRzPCblh+n9N3TAPzSTQocrLx5YuF+fQWyqCCkrkzUFy9EG7Nl5OEFlajS6m8HgigXJzNl83I7f/9HjYGS0vlUdmS97DTdJj1tFgIWEQ/shp+BgdwxD+PzJDfmqF8GXZAqeHkv0vajXxoXxFJ6Uy6rVfuLH5IpiqRFkVSL3W/GmUyrvR3fjlJqZ9sXeTyFHZxHReAHTuOnoKYkAGkS6rD9w5/6htJwFY8=
before_install:
- docker run -d --name ubuntu-test -v $(pwd):/travis ubuntu:$DIST tail -f /dev/null
- docker ps
install:
- docker exec -t ubuntu-test bash -c "apt-get update; apt-get install -y libgtk-3-dev
  gettext appstream-util desktop-file-utils gcc g++ curl meson;"
script:
- travis_wait 45 docker exec -t ubuntu-test bash -c "(curl https://sh.rustup.rs -sSf
  | sh -s -- -y) && source \$HOME/.cargo/env && cd /travis && rustup install $RUST_VER
  && rustc --version && meson _build && ninja -C _build test && cargo rustdoc -- --document-private-items"
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  openssl aes-256-cbc -K $encrypted_63d4c9a7115b_key -iv $encrypted_63d4c9a7115b_iv -in .ci/id_ed25519.enc -out .ci/id_ed25519 -d &&
  sudo chown -R travis:travis ../*
