[package]
name = "gxi"
version = "0.1.0"
authors = ["Brian Vincent <brainn@gmail.com>"]

[dependencies.gtk]
version = "0.1.0"
features = ["v3_10"]

[dependencies]
cairo-rs = "0.1.2"
env_logger = "0.4"
gdk = "0.5.2"
gdk-sys = "0.3.3"
gio = "0.1.0"
gio-sys = "0.3.3"
glib = "0.1.0"
gtk-sys = "0.3.3"
log = "0.3"
pango = "0.1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
