[package]
name = "gxi"
version = "0.6.2"
authors = ["Rasmus Thomsen <oss@cogitri.dev>", "Brian Vincent <brainn@gmail.com>"]
homepage = "https://github.com/Cogitri/gxi"
description = "GTK frontend, written in Rust, for the xi editor"
repository = "https://github.com/Cogtri/gxi"
keywords = ["gxi", "xi"]
categories = ["editor"]
license = "MIT"
edition = "2018"
readme = "README.md"

[features]
default = []

gtk_v3_22 = ["gtk/v3_22"]

[dependencies]
cairo-rs = "0.6"
env_logger = "0.6"
failure = "0.1"
gdk = "0.10"
gio = "0.6"
glib = "0.7"
gtk = {version="0.6", features = ["v3_20"] }
lazy_static = "1"
libc = "0.2"
log = "0.4"
pango = {version="0.6", features = ["v1_38"] }
pangocairo = "0.7"
serde = "1"
serde_json = "1"
serde_derive = "1"
xi-core-lib = { version="0.2.0", path="vendor/xi-editor/rust/core-lib" }
xi-rpc = { version="0.2.0", path="vendor/xi-editor/rust/rpc" }
dirs = "1"
toml = "0.5"
tempfile = "3"
gettext-rs = { version="0.4", features=["gettext-system"] }
crossbeam-queue = "0.1"
crossbeam-channel = "0.3"
human-panic = "1"
syntect="3"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["precommit-hook", "prepush-hook", "run-cargo-clippy", "run-cargo-fmt"]

[profile.release]
lto = true
codegen-units = 1
