[package]
name = "gxi"
version = "0.1.0"
authors = ["Brian Vincent <brainn@gmail.com>"]

[dependencies.gtk]
version = "0.4.0"
features = ["v3_18"]

[dependencies]
cairo-rs = "0.4"
env_logger = "0.5"
gdk = "0.8"
gdk-sys = "0.6"
gio = "0.4"
gio-sys = "0.6"
glib = "0.5"
gtk-sys = "0.6"
log = "0.4"
pango = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
xi-core-lib = { git = "https://github.com/google/xi-editor" }
xi-rpc = { git = "https://github.com/google/xi-editor" }