[package]
name = "gxi"
version = "0.4.4"
authors = ["Brian Vincent <brainn@gmail.com>", "Rasmus Thomsen <rasmus.thomsen@protonmail.com>"]
homepage = "https://github.com/Cogitri/gxi"
description = "GTK frontend, written in Rust, for the xi editor"
repository = "https://github.com/Cogtri/gxi"
keywords = ["gxi", "xi"]
categories = ["editor"]
license = "MIT"
edition = "2018"
readme = "README.md"

[dependencies]
cairo-rs = "0.5"
env_logger = "0.6"
failure = "0.1"
gdk = "0.9"
gio = "0.5"
glib = "0.6"
glib-sys = { version = "0.7", features = ["v2_36"] }
gobject-sys = "0.7"
gtk = { version = "0.5", features = ["v3_20"] }
gtk-sys = { version = "0.7", features = ["v3_20"] }
lazy_static = "1"
libc = "0.2"
log = "0.4"
mio = "0.6.4"
pango = { version = "0.5", features = ["v1_38"] }
pangocairo = "0.6"
serde = "1"
serde_json = "1"
serde_derive = "1"
xi-core-lib = { version="0.2.0", path="vendor/xi-editor/rust/core-lib" }
xi-rpc = { version="0.2.0", path="vendor/xi-editor/rust/rpc" }
dirs = "1"
toml = "0.4"
tempfile = "3"
gettext-rs = "0.4"

[profile.release]
lto = true
codegen-units = 1
