[package]
name = "gxi"
version = "0.2.0"
authors = ["Brian Vincent <brainn@gmail.com>"]

[dependencies]
cairo-rs = "0.4.1"
env_logger = "0.5.9"
gdk = "0.8"
gio = "0.4"
glib = "0.5"
glib-sys = { version = "0.6", features = ["v2_36"] }
gtk = { version = "0.4", features = ["v3_22"] }
lazy_static = "1.0"
libc = "0.2"
log = "0.4"
mio = "0.5"
serde_json = "1.0"
servo-fontconfig = "0.4.0"
syntect = "2.0"
xi-core-lib = { git = "https://github.com/google/xi-editor", rev = "90f90efc" }
xi-rpc = { git = "https://github.com/google/xi-editor", rev = "90f90efc" }
