[package]
name = "gxi"
version = "0.2.0"
authors = ["Brian Vincent <brainn@gmail.com>"]
homepage = "https://github.com/bvinc/gxi"
description = "GTK frontend, written in Rust, for the xi editor"
repository = "https://github.com/bvinc/gxi"
keywords = ["gxi", "xi"]
categories = ["editor"]
license = "MIT"
license-file = "LICENSE"


[dependencies]
cairo-rs = "0.4.1"
clap = "2.31"
env_logger = "0.5.9"
failure = "0.1"
gdk = "0.8"
gio = "0.4"
glib = "0.5"
glib-sys = { version = "0.6", features = ["v2_36"] }
gobject-sys = "0.6"
gtk = { version = "0.4", features = ["v3_22"] }
gtk-sys = { version = "0.6", features = ["v3_22"] }
lazy_static = "1.0"
libc = "0.2"
log = "0.4"
mio = "0.5"
pango = { version = "0.4", features = ["v1_38"] }
pangocairo = "0.5.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
servo-fontconfig = "0.4.0"
xi-core-lib = { git = "https://github.com/google/xi-editor", rev = "a66bbd68" }
xi-rpc = { git = "https://github.com/google/xi-editor", rev = "a66bbd68" }
